#! /bin/sh 
sxhkd &
xset r rate 200 30 &
dunst &
picom -b &
setxkbmap -option grp:lalt_toggle us,ru
xsetroot -cursor_name Bibata-Modern-Classic &
xsetroot -cursor_name left_ptr &
setxkbmap -option ctrl:nocaps &
feh --bg-fil /home/teapot293/wallp/1.png &
polybar &
wmname LG3D &
lxpolkit &

bspc monitor -d  󰲠  󰲢  󰲤  󰎭  󰎱
bspc config border_width         3
bspc config window_gap           5
bspc config normal_border_color "#4C566A"
bspc config focused_border_color "#5E81AC"
bspc config pointer_follows_focus true; 
bspc config single_monocle	     false
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 false
bspc config focus_follows_pointer true
bspc config pointer_modifier	super
bspc rule -a mplay state=floating
#bspc rule -a firefox desktop='^1'
#bspc rule -a code desktop='^2'
#bspc rule -a telegram-desktop desktop='^3'
#bspc rule -a thunar desktop='^4'
#bspc rule -a steam desktop='^5'
